export const useAppStore = defineStore("app", {
  state: () => ({
    services: [
      {
        id: "Industrial&Oil-Field-Spare-Parts",
        name: "Industrial & Oil-Field Spare Parts",
        metaTitle: "Industrial & Oil-Field Spare Parts | Ultimate Equipments",
        metaDesc:
          "Leading supplier of industrial & oil-field spare parts in UAE. We ensure top-quality protection for multinational workforces in construction & industrial sectors.",
        desc: "Industrial and oil-field spare parts refer to components, equipment, and tools that are essential for the smooth operation and maintenance of industrial machinery and oil-field equipment. These spare parts play a crucial role in ensuring the reliability, efficiency, and longevity of various systems in industries and oil exploration and production",
        points: [
          "Bearings",
          "Spacers",
          "Bushes",
          "Cam Followers",
          "Retainer Rings",
          "Nilos Rings",
          "Seals",
          "Breathers",
          "O-Rings",
          "Oil  Gaskets",
        ],
        img: "/services/1.webp",
      },
      {
        id: "Fasteners",
        name: "Fasteners",
        metaTitle: "Fasteners Suppliers in Dubai, UAE | Ultimate Equipments",
        metaDesc:
          "Reliable fasteners supplier in Dubai, UAE. Get high-quality industrial fasteners for construction, oil-field, and manufacturing needs. Contact us today!",
        desc: "This is one of the products with our own  production units in India as well and  hence the expertise to the core maximum.  Below are few of the products we cater in  this category",
        points: [
          "Stud Bolts",
          "Aluminum Sheets",
          "Hex Head Bolts/Nuts & Washers",
          "SS Plates",
          "Threaded Rods",
          "Pipe Clamps",
          "Socket head Cap Screws",
          "Self-Tapping Screws",
          "U Bolts/ J Bolts/ L Bolts",
        ],
        img: "/services/2.webp",
      },
      {
        id: "Power-Tools&Pneumatic-Tools",
        name: "Power Tools & Pneumatic Tools",
        metaTitle: "Power Tools & Pneumatic Tools Dubai, UAE | UMET",
        metaDesc:
          "Top supplier of power & pneumatic tools in Dubai, UAE. Get high-quality tools for construction, manufacturing & industrial use. Contact us today!",
        desc: "We are one among the largest distributors of quality  professional tools with one of the largest range of  pneumatic and power tools and cordless power tools in  the region. Below are few of the tools that we cater",
        points: [
          "Drilling machines",
          "Air Impact Wrench",
          "Rotary Hammers",
          "Air Die Grinder",
          "Concrete Saws",
          "Air Ratchet",
          "Compressors",
          "Air Screw driver",
          "Angle Grinder",
          "Pneumatic Hammer",
        ],
        img: "/services/3.webp",
      },
      {
        id: "Engineering&Hand-Tools",
        name: "Engineering & Hand Tools",
        metaTitle: "Engineering & Hand Tools in UAE | UMET",
        metaDesc:
          "Leading supplier of engineering & hand tools in UAE. Find high-quality tools for industrial, construction & maintenance needs. Contact us today!",
        desc: "Below are the list of tools that we cater from a vast list  of engineering tools that we specialize",
        points: [
          "Spanners",
          "Crimping Pliers",
          "Adjustable Wrenches",
          "Pipe Wrenches",
          "Screwdrivers",
          "Bolt Cutters",
          "Leather Belt Wrenches",
          "Cutting Discs",
          "Side Cutters",
          "Grinding Discs",
          "Monkey Pliers",
        ],
        img: "/services/4.webp",
      },
      {
        id: "5",
        name: "Measuring & Inspection Tools",
        metaTitle: "Measuring & Inspection Tools in UAE | UMET",
        metaDesc:
          "Trusted supplier of measuring & inspection tools in UAE. Our tools include measuring tape, calipers, hardness testers, micro meters, set squares, etc. Call us!",
        desc: "Ultimate Equipments presents a comprehensive range of measuring and testing equipment like measuring tape, calipers, spirit level, and more to meet all your precision needs. Below are some of the products we cater in this category",
        points: [
          "Measuring Tape",
          "Hardness Testers",
          "Calipers",
          "Micro Meters",
          "Set Square",
          "Electronic Weighing Machine",
          "Spirit Level",
          "Temperature & Humidity Testing Machine",
          "Welding Gares",
        ],
        img: "/services/5.webp",
      },
      {
        id: "Safety-Products",
        name: "Safety Products",
        metaTitle: "Industrial Safety Products in UAE | UMET",
        metaDesc:
          "Leading supplier of industrial safety products in UAE. Get top-quality, safety gear shoes, masks & others equipment for construction. Contact us today!",
        desc: "Early recognition for the need of proper protection to the ever  growing multi-national work force not only in the Construction  field but also in the Oil-field & Industrial sector; resulted in us  bringing in TOP names in SAFETY PRODUCTS today namely 3M  (AO Safety, EAR, Peltor & Safewaze), ANSELL, JCB, HONEYWELL. We understand the importance of SAFETY to the end user and  therefore have selected some of the finest products in the  market along with complete range i.e. HEAD to TOE protection.  Our range of Safety Eyewear, Respirators and Hearing Protection  has been carefully put together taking into consideration the  Ergonomic Features, Local Environment, Demographics and  Fashion at the same time not compromising on the SAFETY  STANDARDS which meet with CE or ANSI/CSA standard",
        points: [
          "Coveralls",
          "Safety Vests",
          "Safety Shoes",
          "Earmuff",
          "Safety Helmets",
          "Safety Masks",
          "Impact Gloves",
          "Tripod Kits",
          "Safety Goggle all Types",
          "Gas Monitors (425 Monitor Etc..)",
          "Safety Harness",
          "Safety Sinages",
        ],
        img: "/services/6.webp",
      },
      {
        id: "Lifting-Equipment",
        name: "Lifting Equipment",
        metaTitle: "Lifting Equipment Suppliers in UAE | UMET",
        metaDesc:
          "Leading lifting equipment suppliers of shackles, lifting chains, chain hoists, pulleys, liver hoists, wire ropes & webbing slings in UAE. Contact us today!",
        desc: "We understand the importance of safety  in this part of equipment and hence we  make sure that we only cater from the  major established brands in this category  with approved certificates and test of  conformance. Below are few of the major  equipment that we cater",
        points: [
          "Shackles",
          "Lifting Chains",
          "Chain Hoist",
          "Lifting Pulley",
          "Liver Hoist",
          "Wire Ropes",
          "Webbing Slings",
        ],
        img: "/services/7.webp",
      },
      {
        id: "Welding-Equipment-Cutting&Welding-Consumable",
        name: "Welding and Cutting Equipment",
        metaTitle: "Welding Equipment Suppliers in Dubai, UAE | UMET",
        metaDesc:
          "Top welding equipment suppliers in Dubai, UAE. Get premium cutting & welding consumables for all industrial & construction needs. Contact us today!",
        desc: "With an extensive inventory,  this is one among our major  products",
        points: [
          "Welding Machines",
          "Cutting Hose",
          "Welding Electrodes",
          "Stick Electrodes",
          "Filler Wire",
          "Solid Wires",
          "Welding Helmets",
          "Flux Core Wires",
          "Welding Gloves",
          "Saw Wires",
          "Cutting Torch",
          "Fluxs",
          "Regulators",
          "Others (Including Gases)",
        ],
        img: "/services/8.webp",
      },
      {
        id: "Electrical&Plumbing-Materials",
        name: "Electrical & Plumbing Materials",
        metaTitle: "Plumbing Items & Electrical Materials in Dubai, UAE | UMET",
        metaDesc:
          "Reliable supplier of plumbing items & electrical materials in Dubai, UAE. Get high-quality products for your construction & industrial projects.",
        desc: "Ultimate Equipments offers an extensive range of high-quality electric and plumbing materials like electrical cables, pipes & fittings, sanitary fittings, breakers, and more to meet your needs. Below are some of the products we cater in this category",
        points: [
          "Electrical Cables",
          "Pipes & Fittings",
          "Cable Trays and Trunkings",
          "Valves",
          "Isolators",
          "Sanitary Fittings",
          "Breakers",
          "Transformers",
          "VFD Units",
          "Alarm's Light",
          "Electrical Motors",
          "Blowers and Fans",
        ],
        img: "/services/9.webp",
      },
    ],
    sp_brands: [
      "/images/brands-home/1.png",
      "/images/brands-home/2.png",
      "/images/brands-home/3.png",
      "/images/brands-home/4.png",
      "/images/brands-home/5.png",
      "/images/brands-home/6.png",
      "/images/brands-home/7.png",
      "/images/brands-home/8.png",
      "/images/brands-home/9.png",
      "/images/brands-home/10.png",
      "/images/brands-home/11.png",
      "/images/brands-home/12.png",
      "/images/brands-home/13.png",
      "/images/brands-home/14.png",
      "/images/brands-home/15.png",
      "/images/brands-home/16.png",
      "/images/brands-home/17.png",
      "/images/brands-home/18.png",
      "/images/brands-home/19.png",
      "/images/brands-home/20.png",
      "/images/brands-home/21.png",
      "/images/brands-home/22.png",
      "/images/brands-home/23.png",
      "/images/brands-home/24.png",
      "/images/brands-home/25.png",
      "/images/brands-home/26.png",
      "/images/brands-home/27.png",
      "/images/brands-home/28.png",
    ],
    icons: [
      "/images/clients/magenta.png",
      "/images/clients/mhps.jpeg",
      "/images/clients/enova.png",
      "/images/clients/almansoori.png",
      "/images/clients/nov.png",
      "/images/clients/altrad.png",
      "/images/clients/serco.png",
      "/images/clients/yas.png",
    ],
  }),
  getters: {
    getService: (state) => {
      return (id: string) => state.services.find((service) => service.id == id);
    },
  },
});
